### PR TITLE
Styling formatting rework

### PR DESCRIPTION
**Pull request by ThijsMaas**
Hi @HadrienG,
As promised, here is the PR that includes only the restyling and formatting of the code base.
It is formatted using [black](https://github.com/psf/black) and [isort](https://github.com/PyCQA/isort) and I also checked the codestyle with [flake8](https://github.com/PyCQA/flake8) and fixed the errors it found. 

These tools have setting files, which contain some defaults. 
Specifically, I set the line-length to 120, which is higher than the default 88 of black, but in my opinion this is very reasonable with our large screen sizes and modern IDEs. 

I'm trying to add the checking functionality of each of these tools to the github action. They currently run in our ENPICOM fork, so they don't show up here.

### CODE REVIEW

**Comment by HadrienG** [comment]
@ThijsMaas LGTM but I see that the tests are failing on your fork (due to a missing dependency for black?)

**Comment by ThijsMaas** [comment]
@HadrienG The lint tests work now, apparently Black has different dependencies below Python version 3.11. I don't have the secrets for codecov, so that part still fails, not sure if there is a way around that?

**Comment by HadrienG** [comment]
> @HadrienG The lint tests work now, apparently Black has different dependencies below Python version 3.11. I don't have the secrets for codecov, so that part still fails, not sure if there is a way around that?

You could try to add `if: github.event.repository.fork == false` between line 28 and 29 in `.github/workflows/pythonpackage.yml` (if block same indentation as name and uses)

**Comment by ThijsMaas** [comment]
That solved it, thanks!

**Review by HadrienG — APPROVED** [review]

**Pull request merged**
