### PR TITLE
Fixed the Dockerfile

### PR DESCRIPTION
**Pull request by StefanLelieveld**
**Issue:** Docker-image is not working correctly for v2.0.0 (locally). And is not working on https://hub.docker.com/r/hadrieng/insilicoseq

- Updated the Dockerfile: The v2.0.0 docker image works. 
- Added script docker-build.sh: Builds a multi architecture Docker-image for AMD and ARM. @HadrienG I have left the REGISTRY value open in the script for you to fill in. I have tested the script on our docker-registry and as far as I could test it worked. Please let me know if it does the trick for you too.

### CODE REVIEW

**Comment by HadrienG** [comment]
Thanks @StefanLelieveld . If we go this route I'd also like to automate this with github actions.

Alternatively, I'm wondering why would we still maintain this instead of pointing to the biocontainer that bioconda builds automatically? then all we have to do is change all the paths to `quay.io/biocontainers/insilicoseq:2.0.0--pyh7cba7a3_0` in the documentation.

Lemme know what you think
/Hadrien

**Comment by StefanLelieveld** [comment]
> Thanks @StefanLelieveld . If we go this route I'd also like to automate this with github actions.
> 
> Alternatively, I'm wondering why would we still maintain this instead of pointing to the biocontainer that bioconda builds automatically? then all we have to do is change all the paths to `quay.io/biocontainers/insilicoseq:2.0.0--pyh7cba7a3_0` in the documentation.
> 
> Lemme know what you think /Hadrien

Hi Hadrien,

I just had a chat with Thijs and we like the alternative approach you propose. I will remove the Dockerfile + docker-build.sh and change the docker-image in the README to the biocontainer docker-image you provided.

best,
Stefan

**Comment by StefanLelieveld** [comment]
>  I will remove the Dockerfile + docker-build.sh and change the docker-image in the README to the biocontainer docker-image you provided.

Update on the matter: The Biocontainer docker image is not build for the ARM architecture (only for AMD?). This might be a reason to use the Dockerfile (and multi-arch build script) to provide support for both architectures in one solution. 

@HadrienG  @ThijsMaas what would your opinion? Support ARM architectures too?

**Review by ThijsMaas — APPROVED** [review]
Good solution! Lets get this out before user try to test this and it doesn't work for them

**Review by HadrienG — APPROVED** [review]

**Pull request merged**
